Plant.create!(name:'Agastache', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/AGA.jpg')
Plant.create!(name:'Ageratum', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/AGE.jpg')
Plant.create!(name:'Allium (Ornamental)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ALL.jpg')
Plant.create!(name:'Almond', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ALM.jpg')
Plant.create!(name:'Alyssum', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ALY.jpg')
Plant.create!(name:'Amaranth (Grain)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/AMA.jpg')
Plant.create!(name:'Amaranth (Ornamental)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/AMA2.jpg')
Plant.create!(name:'Anemone', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ANE.jpg')
Plant.create!(name:'Apple (Cordon)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/APP3.jpg')
Plant.create!(name:'Apple (Dwarf)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/APP1.jpg')
Plant.create!(name:'Apple (Espalier)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/APP4.jpg')
Plant.create!(name:'Apple (Large)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/APP2.jpg')
Plant.create!(name:'Apricot (Dwarf)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/APR1.jpg')
Plant.create!(name:'Apricot (Large)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/APR2.jpg')
Plant.create!(name:'Artichoke (Globe)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ART.jpg')
Plant.create!(name:'Arugula', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ARU.jpg')
Plant.create!(name:'Asparagus', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ASP.jpg')
Plant.create!(name:'Aster (China)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/AST.jpg')
Plant.create!(name:'Basil', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BAS.jpg')
Plant.create!(name:'Bay', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BAY.jpg')
Plant.create!(name:'Beans (Bush Snap)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BEA2.jpg')
Plant.create!(name:'Beans (Dry)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BEA6.jpg')
Plant.create!(name:'Beans (Fava)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BEA1.jpg')
Plant.create!(name:'Beans (Lima)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BEA4.jpg')
Plant.create!(name:'Beans (Pole)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BEA3.jpg')
Plant.create!(name:'Beet', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BEE.jpg')
Plant.create!(name:'Begonia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BEG.jpg')
Plant.create!(name:'Bells of Ireland', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BEL.jpg')
Plant.create!(name:'Black Currant', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BLA2.jpg')
Plant.create!(name:'Blackberry', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BLA.jpg')
Plant.create!(name:'Bluebell', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BLU2.jpg')
Plant.create!(name:'Blueberry', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BLU.jpg')
Plant.create!(name:'Bok Choy', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BOK.jpg')
Plant.create!(name:'Borage', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BOR.jpg')
Plant.create!(name:'Broccoli', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BRO2.jpg')
Plant.create!(name:'Broccoli (Purple Sprouting)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BRO.jpg')
Plant.create!(name:'Brussels Sprouts', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BRU.jpg')
Plant.create!(name:'Buckwheat', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/BUC.jpg')
Plant.create!(name:'Cabbage (Fall Red)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAB6.jpg')
Plant.create!(name:'Cabbage (Fall)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAB2.jpg')
Plant.create!(name:'Cabbage (Spring Red)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAB7.jpg')
Plant.create!(name:'Cabbage (Spring)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAB3.jpg')
Plant.create!(name:'Cabbage (Summer Red)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAB5.jpg')
Plant.create!(name:'Cabbage (Summer)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAB1.jpg')
Plant.create!(name:'Calendula', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAL2.jpg')
Plant.create!(name:'Cantaloupe', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAN.jpg')
Plant.create!(name:'Carrot', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAR.jpg')
Plant.create!(name:'Catnip', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAT.jpg')
Plant.create!(name:'Cauliflower', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAU.jpg')
Plant.create!(name:'Celeriac', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CEL2.jpg')
Plant.create!(name:'Celery', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CEL.jpg')
Plant.create!(name:'Celosia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CEL3.jpg')
Plant.create!(name:'Chamomile', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CHA.jpg')
Plant.create!(name:'Cherry (Dwarf)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CHE1.jpg')
Plant.create!(name:'Cherry (Fan)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CHE3.jpg')
Plant.create!(name:'Cherry (Semi-Dwarf)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CHE2.jpg')
Plant.create!(name:'Chestnut (Chinese)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CHE.jpg')
Plant.create!(name:'Chicory', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CHI.jpg')
Plant.create!(name:'Chili Pepper', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEP1.jpg')
Plant.create!(name:'Chinese Cabbage', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CAB4.jpg')
Plant.create!(name:'Chives', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CHI2.jpg')
Plant.create!(name:'Chives (Garlic)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CHI3.jpg')
Plant.create!(name:'Cilantro', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CIL.jpg')
Plant.create!(name:'Cleome', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CLE.jpg')
Plant.create!(name:'Colchicum', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/COL3.jpg')
Plant.create!(name:'Coleus', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/COL2.jpg')
Plant.create!(name:'Collards', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/COL.jpg')
Plant.create!(name:'Comfrey', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/COM.jpg')
Plant.create!(name:'Convolvulus', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CON.jpg')
Plant.create!(name:'Coreopsis', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/COR5.jpg')
Plant.create!(name:'Corn', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/COR.jpg')
Plant.create!(name:'Cornflower', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/COR4.jpg')
Plant.create!(name:'Cosmos', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/COS.jpg')
Plant.create!(name:'Cotton', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/COT.jpg')
Plant.create!(name:'Cranberry', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CRA.jpg')
Plant.create!(name:'Cress', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CRE.jpg')
Plant.create!(name:'Crimson Clover', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CLO.jpg')
Plant.create!(name:'Crocus', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CRO2.jpg')
Plant.create!(name:'Crowder Peas', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CRO.jpg')
Plant.create!(name:'Cucumber', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CUC.jpg')
Plant.create!(name:'Cuphea', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CUP.jpg')
Plant.create!(name:'Daffodil', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/DAF.jpg')
Plant.create!(name:'Dahlia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/DAH.jpg')
Plant.create!(name:'Daylily', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/DAY.jpg')
Plant.create!(name:'Dianthus', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/DIA.jpg')
Plant.create!(name:'Dill', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/DIL.jpg')
Plant.create!(name:'Dusty Miller', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/CIN.jpg')
Plant.create!(name:'Echinacea', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ECH.jpg')
Plant.create!(name:'Edamame', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/EDA.jpg')
Plant.create!(name:'Eggplant', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/EGG.jpg')
Plant.create!(name:'Endive', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/END.jpg')
Plant.create!(name:'Fennel', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FEN.jpg')
Plant.create!(name:'Fennel (Herb)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FEN2.jpg')
Plant.create!(name:'Fenugreek', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FEN3.jpg')
Plant.create!(name:'Feverfew', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FEV.jpg')
Plant.create!(name:'Fig', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FIG.jpg')
Plant.create!(name:'Fig (Container Grown)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FIG2.jpg')
Plant.create!(name:'Filbert', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FIL.jpg')
Plant.create!(name:'Fruit (Bush)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FRU1.jpg')
Plant.create!(name:'Fruit (Dwarf Tree)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FRU2.jpg')
Plant.create!(name:'Fruit (Trellised)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FRU3.jpg')
Plant.create!(name:'Gaillardia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GAI.jpg')
Plant.create!(name:'Garlic', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GAR.jpg')
Plant.create!(name:'Gazania', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GAZ.jpg')
Plant.create!(name:'Geranium', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GER.jpg')
Plant.create!(name:'Ginger', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GIN.jpg')
Plant.create!(name:'Gladiolus', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GLA.jpg')
Plant.create!(name:'Gomphrena', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GOM.jpg')
Plant.create!(name:'Gooseberry', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GOO.jpg')
Plant.create!(name:'Gourd', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GOU.jpg')
Plant.create!(name:'Grape Vine', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GRA.jpg')
Plant.create!(name:'Gypsophila', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/GYP.jpg')
Plant.create!(name:'Hairy Vetch', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/VET.jpg')
Plant.create!(name:'Hazel', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/HAZ.jpg')
Plant.create!(name:'Heliotrope', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/HEL.jpg')
Plant.create!(name:'Herb', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/HER.jpg')
Plant.create!(name:'Honeyberry', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/HON.jpg')
Plant.create!(name:'Hops', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/HOP.jpg')
Plant.create!(name:'Horseradish', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/HOR.jpg')
Plant.create!(name:'Hyacinth', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/HYA.jpg')
Plant.create!(name:'Impatiens', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/IMP.jpg')
Plant.create!(name:'Iris', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/IRI.jpg')
Plant.create!(name:'Jerusalem Artichoke', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/JER.jpg')
Plant.create!(name:'Johnny Jump Up', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/VIO.jpg')
Plant.create!(name:'Jostaberry', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/JOS.jpg')
Plant.create!(name:'Kale', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/KAL.jpg')
Plant.create!(name:'Kiwi', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/KIW.jpg')
Plant.create!(name:'Kohlrabi', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/KOH.jpg')
Plant.create!(name:'Lantana', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LAN.jpg')
Plant.create!(name:'Larkspur', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LAR.jpg')
Plant.create!(name:'Lavatera', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LAV2.jpg')
Plant.create!(name:'Lavender', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LAV.jpg')
Plant.create!(name:'Leek', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LEE.jpg')
Plant.create!(name:'Lemon', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LEM4.jpg')
Plant.create!(name:'Lemon (Container Grown)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LEM5.jpg')
Plant.create!(name:'Lemon Balm', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LEM.jpg')
Plant.create!(name:'Lemon Verbena', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LEM2.jpg')
Plant.create!(name:'Lemongrass', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LEM3.jpg')
Plant.create!(name:'Lettuce (Crisphead)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LET2.jpg')
Plant.create!(name:'Lettuce (Leaf)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LET1.jpg')
Plant.create!(name:'Lettuce (Miners)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LET4.jpg')
Plant.create!(name:'Lily', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LIL.jpg')
Plant.create!(name:'Lime', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LIM.jpg')
Plant.create!(name:'Lime (Container Grown)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LIM2.jpg')
Plant.create!(name:'Lobelia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LOB.jpg')
Plant.create!(name:'Loganberry', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LOG.jpg')
Plant.create!(name:'Lovage', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/LOV.jpg')
Plant.create!(name:'Mache', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MAC.jpg')
Plant.create!(name:'Marigold', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MAR2.jpg')
Plant.create!(name:'Marjoram', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MAJ.jpg')
Plant.create!(name:'Medlar', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MED.jpg')
Plant.create!(name:'Melon', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MEL.jpg')
Plant.create!(name:'Mint', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MIN.jpg')
Plant.create!(name:'Mizuna', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MIZ.jpg')
Plant.create!(name:'Monarda', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MON.jpg')
Plant.create!(name:'Morning Glory', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MGL.jpg')
Plant.create!(name:'Muscari', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MUS2.jpg')
Plant.create!(name:'Muskmelon', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MSK.jpg')
Plant.create!(name:'Mustard', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/MUS.jpg')
Plant.create!(name:'Nasturtium', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/NAS.jpg')
Plant.create!(name:'Nectarine (Dwarf)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/NEC1.jpg')
Plant.create!(name:'Nectarine (Large)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/NEC2.jpg')
Plant.create!(name:'Nicotiana', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/NIC.jpg')
Plant.create!(name:'Nigella', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/NIG.jpg')
Plant.create!(name:'Oats', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/OAT.jpg')
Plant.create!(name:'Okra', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/OKR.jpg')
Plant.create!(name:'Onion', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ONI.jpg')
Plant.create!(name:'Onion (Fall planted)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ONI5.jpg')
Plant.create!(name:'Onions (Green)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ONI2.jpg')
Plant.create!(name:'Onions (Perennial)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ONI3.jpg')
Plant.create!(name:'Onions (Red)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ONI4.jpg')
Plant.create!(name:'Orange', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ORA.jpg')
Plant.create!(name:'Orange (Container Grown)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ORA2.jpg')
Plant.create!(name:'Oregano', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ORE.jpg')
Plant.create!(name:'Osteospermum', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/OST.jpg')
Plant.create!(name:'Pansy', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PAN.jpg')
Plant.create!(name:'Parsley', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PAR2.jpg')
Plant.create!(name:'Parsnip', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PAR.jpg')
Plant.create!(name:'Peach (Dwarf)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEA8.jpg')
Plant.create!(name:'Peach (Large)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEA9.jpg')
Plant.create!(name:'Peanut', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEA3.jpg')
Plant.create!(name:'Pear (Cordon)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEA6.jpg')
Plant.create!(name:'Pear (Dwarf)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEA4.jpg')
Plant.create!(name:'Pear (Espalier)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEA7.jpg')
Plant.create!(name:'Pear (Large)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEA5.jpg')
Plant.create!(name:'Peas', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEA.jpg')
Plant.create!(name:'Pecan', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEC.jpg')
Plant.create!(name:'Pepper', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEP.jpg')
Plant.create!(name:'Persimmon', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PER.jpg')
Plant.create!(name:'Petunia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PET2.jpg')
Plant.create!(name:'Phacelia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PHA.jpg')
Plant.create!(name:'Phlox (Annual)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PHL.jpg')
Plant.create!(name:'Plum (Dwarf)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PLU1.jpg')
Plant.create!(name:'Plum (Fan)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PLU3.jpg')
Plant.create!(name:'Plum (Large)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PLU2.jpg')
Plant.create!(name:'Poached Egg Plant', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/POA.jpg')
Plant.create!(name:'Pomegranate', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/POM.jpg')
Plant.create!(name:'Portulaca', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/POR.jpg')
Plant.create!(name:'Potatoes (Early)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/POT1.jpg')
Plant.create!(name:'Potatoes (Maincrop)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/POT2.jpg')
Plant.create!(name:'Pumpkin', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PUM.jpg')
Plant.create!(name:'Quinoa', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/QUI.jpg')
Plant.create!(name:'Radicchio', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/RAD2.jpg')
Plant.create!(name:'Radish', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/RAD.jpg')
Plant.create!(name:'Raspberry', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/RAS.jpg')
Plant.create!(name:'Red Currant', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/RED.jpg')
Plant.create!(name:'Rhubarb', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/RHU.jpg')
Plant.create!(name:'Rose', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ROS2.jpg')
Plant.create!(name:'Rosemary', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ROS.jpg')
Plant.create!(name:'Rutabaga', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/RUT.jpg')
Plant.create!(name:'Rye (Annual)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/RYE1.jpg')
Plant.create!(name:'Rye (Cereal)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/RYE2.jpg')
Plant.create!(name:'Sage', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SAG.jpg')
Plant.create!(name:'Salpiglossis', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SAL2.jpg')
Plant.create!(name:'Salvia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SAL3.jpg')
Plant.create!(name:'Scabiosa (Sweet)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SCA2.jpg')
Plant.create!(name:'Scallions', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SCA.jpg')
Plant.create!(name:'Scarlet Sage', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SAG2.jpg')
Plant.create!(name:'Scilla', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SCI.jpg')
Plant.create!(name:'Shallots', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SHA.jpg')
Plant.create!(name:'Snapdragon', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SNA.jpg')
Plant.create!(name:'Snowdrop', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SNO.jpg')
Plant.create!(name:'Sorrel', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SOR.jpg')
Plant.create!(name:'Soybeans', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SOY.jpg')
Plant.create!(name:'Spinach', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SPI.jpg')
Plant.create!(name:'Spinach (Malabar)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SPI4.jpg')
Plant.create!(name:'Spinach (New Zealand)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SPI2.jpg')
Plant.create!(name:'Squash (Summer)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SQU2.jpg')
Plant.create!(name:'Squash (Winter)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SQU.jpg')
Plant.create!(name:'Stevia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/STE.jpg')
Plant.create!(name:'Stock', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/STO.jpg')
Plant.create!(name:'Strawberry', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/STR.jpg')
Plant.create!(name:'Strawflower', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/STR2.jpg')
Plant.create!(name:'Sunflower', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SUN.jpg')
Plant.create!(name:'Sweet Pea', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SPE.jpg')
Plant.create!(name:'Sweet Potato', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SWE2.jpg')
Plant.create!(name:'Swiss Chard', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/SWI.jpg')
Plant.create!(name:'Tansy', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/TAN.jpg')
Plant.create!(name:'Tarragon', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/TAR.jpg')
Plant.create!(name:'Tatsoi', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/TAT.jpg')
Plant.create!(name:'Thyme', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/THY.jpg')
Plant.create!(name:'Tomatillo', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/TOM3.jpg')
Plant.create!(name:'Tomato (Large)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/TOM2.jpg')
Plant.create!(name:'Tomato (Small)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/TOM1.jpg')
Plant.create!(name:'Tulip', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/TUL.jpg')
Plant.create!(name:'Turnip', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/TUR.jpg')
Plant.create!(name:'Valerian', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/VAL.jpg')
Plant.create!(name:'Verbena (Annual)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/VER.jpg')
Plant.create!(name:'Vinca (Annual)', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/VIN.jpg')
Plant.create!(name:'Walnut', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/WAL.jpg')
Plant.create!(name:'Watermelon', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/WAT.jpg')
Plant.create!(name:'Wheat', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/WHE.jpg')
Plant.create!(name:'White Currant', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/WHI.jpg')
Plant.create!(name:'Winter Field Beans', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/FIE.jpg')
Plant.create!(name:'Winter Peas', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/PEA2.jpg')
Plant.create!(name:'Zinnia', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ZIN.jpg')
Plant.create!(name:'Zucchini', photo_url:'https://www.growveg.com/assets/images/plants/smaller_thumbnails/ZUC.jpg')